version: 2.1

orbs:
  maven: circleci/maven@0.0.12

shared: &shared
  steps:
    - checkout
    - restore_cache:
        key: sortpom-cache-{{ checksum "pom.xml" }}
    - run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -Dinvoker.skip=true -B -V
    - run: mvn integration-test -B
    - save_cache:
        paths:
          - ~/.m2
        key: sortpom-cache--{{ checksum "pom.xml" }}
      
jobs:
  jdk8:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    <<: *shared
  jdk11:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: sortpom-cache-{{ checksum "pom.xml" }}
      - run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -Dinvoker.skip=true -B -V
      - run: mvn clean jacoco:prepare-agent integration-test jacoco:report -B
      - run: mvn coveralls:report -B -DrepoToken=$COVERALLS_REPO_TOKEN
      - run: mvn sonar:sonar -Dsonar.projectKey=com.github.ekryd.sortpom:sortpom-parent -Dsonar.organization=ekryd-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN
      - save_cache:
          paths:
            - ~/.m2
          key: sortpom-cache--{{ checksum "pom.xml" }}
        
workflows:
  work:
    jobs:
#      - jdk8
      - jdk11
        
